### PR TITLE
Adding BOOST_NO_AUTO_PTR define

### PR DESCRIPTION
**Pull request by mortenvp**
Removes warnings regarding use of the deprecated auto_ptr

### CODE REVIEW

**Comment by petya2164** [comment]
@mortenvp Why is this a major?
We do not break any of the API with this :)

**Comment by mortenvp** [comment]
Yeah, I know :) I thought the safe thing was to go with a major since defining this will basically remove some code in boost.. but I guess it is extremely unlikely to affect any existing code - unless somebody somewhere used an auto_ptr ..

**Comment by petya2164** [comment]
I would classify this as a patch (we are only suppressing warnings) and run the depcheck to confirm that it does not change anything.

**Comment by mortenvp** [comment]
Running the dependency check now..

**Comment by mortenvp** [comment]
I think the safe thing to do here is to mark it as major so I will go with that.

**Pull request merged**
